### ISSUE TITLE
be able to tag data as "science" vs "engineering"

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_mc#156]

**Comment by jack-h** [comment]
I'm going to add a field which ends up in the data files for an observation tag (

**Comment by jack-h** [comment]
Wow. Mega ineffective github-ing.

I'm going to add to the correlator interface an option to tag data files with a string when you start the correlator, to at least give some minimal record of what the observer's intention was.

**Comment by bhazelton** [comment]
This is implemented in M&C. @jack-h does this tag go into the file header already?

**Comment by jack-h** [comment]
This is implemented in the files as of fab0dadf (i.e., Just Now).

The missing link is the correlator actually responding to MC. Working on that now....

**Comment by bhazelton** [comment]
@jack-h can this be closed? Are these tags written into the files?

**Comment by jack-h** [comment]
Yes. Close at leisure.
