### ISSUE TITLE
Metadata 'sets' from new analog system

### ISSUE THREAD

**Issue by miguelfmorales** [HERA-Team/hera_mc#160]
The new receiver and PAMs presented in Socorro will have a _ton_ of sensors. In addition to temperature, there is a 9-axis accelerometer and a barometer on board and a number of other new sensors (talk not up yet), all of which can be queried. 

It was clear that Nima was expecting all of these to be individually addressable, and that sounded like a nightmare to M&C.

So I'd like to propose that there is 1 or 2 'sets' of metadata that the system can report. A set is a pairing of a command (maybe on a heartbeat?) that says send me this set of metadata, and a packet from the system that returns with all of the associated values filled in. In this model there would either be a 'send me all the data' as the single command, or a 'send me temperature' and 'send me everything' for the 2 set system. 

The goal is to think about what the use pattern we want is, and to greatly reduce the number of command/response pairs we need to implement and test.

**Comment by bhazelton** [comment]
This is part of the plan for the correlator/M&C interface, we'll do it the same way we're querying the nodes at the moment.
