### ISSUE TITLE
Use tabulate's HTML output format for HTML output

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/hera_mc#165]
Right now the status webpage is written out by printing the hookup/levels in ASCII as normal, then wrapping the output in `<pre>` tags. The `tabulate` package has an HTML output format that might look better.

**Comment by david-deboer** [comment]
I tried this, and in fact the ascii one is easier to read.  The html version doesn't have separators, the columns run together a bit and the headings are as well aligned.
