### ISSUE TITLE
New a priori antenna status table

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_mc#219]
Add 2 tables to handle known antenna status (see Commissioning Minutes of 3/9/18):
1 - antenna, start_gpstime, stop_gpstime, status keyword (foreign-keyed to...)
2 - status keyword, description

**Comment by david-deboer** [comment]
initial proposed keywords:

candidate - built but not tested/confirmed
bad - bad apple for now

**Comment by bhazelton** [comment]
Make this also useful for RTP to know when to check for cross polarizations.

**Comment by bhazelton** [comment]
Maybe also replaces the dubitable table.

**Comment by david-deboer** [comment]
Paul come up with initial keyword/state set

**Comment by bhazelton** [comment]
Proposal:
- antenna number
- starttime
- stoptime
- status (enum: 'passed_checks', 'needs_checking', 'known_bad')

remove 'dubitable' table.
