### ISSUE TITLE
take plotting symbols and colors out of database tables

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#22]
make it a more flexible choice of plotting code instead. Keep the station types identified.

**Comment by david-deboer** [comment]
I decided to leave that in for these special sub-types.  Sort of nice and sort of no-harm-no-foul.  The geo stuff has been fairly majorly rewritten, so a few things (primarily cofa?) might be broken.  Difference should mostly be to import geo_handling rather than geo_location
