### ISSUE TITLE
python 3 compatibility

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#229]

**Comment by pkgw** [comment]
At the moment I think we're only blocking on `hera_qm` becoming Python-3-compatible, at least in terms of the test suite passing. It might be good to disable that test for the time being and start CI'ing Python 3 anyway, so that we don't accidentally re-introduce Python-2-only-isms.

**Comment by bhazelton** [comment]
That sounds reasonable, I'll make a PR
