### ISSUE TITLE
Local csv to sqlite module for cm_lite

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_mc#25]
Add feature to make new local sqlite from csv for local use of cm scripts

**Comment by bhazelton** [comment]
@david-deboer should this issue still be open?

**Comment by bhazelton** [comment]
@david-deboer should this issue still be open?

**Comment by pkgw** [comment]
We've chatted about this recently on the telecons and my takeaway is that yes, it should. I suspect that this issue is really going to not take very much code to fix, but a moderate amount of sitting down and thinking how to architect it.

**Comment by david-deboer** [comment]
I've implemented this.  Only changes needed are to the mc_config.json file (described in INSTALL.md) and you must update hera_cm_db_updates (which as the sqlite file hera_mc.db in it).

**Comment by pkgw** [comment]
Fixed by @david-deboer in #194.
