### ISSUE TITLE
Get version info from SNAPs into M&C 

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#279]

**Comment by bhazelton** [comment]
Talk with Jack about any other versions we should be tracking

**Comment by bhazelton** [comment]
PR #293 gets us part way there with the file name, but it doesn't include the full git info (branch, hash)

**Comment by david-deboer** [comment]
Want to include node software, F-software, etc

**Comment by jack-h** [comment]
significantly addressed in https://github.com/HERA-Team/hera_corr_cm/commit/11a573c9938b045e6a85cd695911878f823c0a90

**Comment by bhazelton** [comment]
Is there anything left that's not having version info reported?

**Comment by bhazelton** [comment]
This has been met by the current state.
