### ISSUE TITLE
geo.py plots current antennas regardless of date

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#281]
For example the command
`geo.py -g --date=2016/11/08`
returns
![image](https://user-images.githubusercontent.com/63191/47968973-4d039d00-e02e-11e8-894b-5b3bb01c87c7.png)

**Comment by dannyjacobs** [comment]
I think its line 390 in  geo_handling.plot_station_types
fig_num = self.plot_stations(self.station_types[st]['Stations'], query_date, **kwargs)

I think that which gets defined as "Stations" in the station_types is not recomputed depending on the date. Either the station_types should be recomputed or plot_stations should use the query_date is its passed to filter out things which don't yet exist.  
Ideally the filter would take place at one obvious place.

**Comment by david-deboer** [comment]
I'm simplifying this (hopefully synonymous with fixing...) hopefully by tomorrow.
