### ISSUE TITLE
Use or remove hera_mc/args_test.py file

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#29]

**Comment by pkgw** [comment]
@david-deboer I am confused about the file `hera_mc/args_test.py`. If I do a `git grep` I just don't see `args_test` being used anywhere in the code. Can you clarify what the purpose of this file is?

**Comment by david-deboer** [comment]
If I want to test aspects of code from within ipython you need an args generator.  So, it is only useful to set up an args there.  I haven’t used it much, but it is helpful to have around.

So, it is an args-for-interactive-testing, not a test-for-args

**Comment by david-deboer** [comment]
I can annotate the file, but I'd suggest we keep it and close the issue.

**Comment by pkgw** [comment]
Renamed to `args4testing.py`, purpose explained somewhat in a header comment.
