### ISSUE TITLE
Correlator knows what paths are good somehow (separate from CM). Get that info into M&C

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#298]

**Comment by david-deboer** [comment]
I spoke with Jack -- the correlation isn't cognizant of array goodness beyond CM.

**Comment by bhazelton** [comment]
@plaplant can you chime in here? I'm confused about how this fits with our conversation.

**Comment by plaplant** [comment]
@jack-h my understanding was that the correlaltor was aware of which antennas it actually received data from, because those entries where the only valid numbers in, e.g., `ant_1_array`. Is that not true?

**Comment by david-deboer** [comment]
As I understand, he takes the result from the cminfo to determine the valid antennas, which then get mapped to his numbers.

**Comment by bhazelton** [comment]
Ok, then I'm going to close this issue. Thanks for clarifying @jack-h !
