### ISSUE TITLE
Correlator monitor is broken because of too many redis connections

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#308]
@jack-h I think this needs to be fixed in hera_corr_cm. I think we need a `close` method to close the connection.

**Comment by jack-h** [comment]
Commit 96f03bf of hera_corr_cm shoudl resolve this. Let me know if it doesn't

**Comment by bhazelton** [comment]
We're still seeing the errors. I just realized that your changes hadn't been installed on site, but I did that install and we're continuing to see the errors. Perhaps the problem is that it can't be fixed until the old connections are closed in some way? I'm not sure how to do that.

**Comment by jack-h** [comment]
Hmmm.

Is there a particular cm script i can run to try to recreate this issue?

**Comment by bhazelton** [comment]
should be fixed now.
