### ISSUE TITLE
white rabbit (clock system) monitor info

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#343]
node clock & master locking status, gps status

should come through the node control system.

**Comment by bhazelton** [comment]
@jack-h are you the person for this or is it someone else?

**Comment by jack-h** [comment]
Unfortunately I am. Need to figure out how to do this

**Comment by jack-h** [comment]
Added Node timing monitor info in https://github.com/HERA-Team/hera_node_mc/commit/b9bd54c4d4eed0e34a321ed67ea554b5477b5a57

**Comment by jack-h** [comment]
(sorry, not sure if I told you this when I did it)

**Comment by bhazelton** [comment]
done in PR #445
