### ISSUE TITLE
Provide info so that correlator can write correct UVWs into data files (NSF milestone due 2017 Aug 1)

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/hera_mc#36]
We need to set up a bridge between M&C and the correlator such that the correlator can get the antenna position and hookup information from M&C and get the right UVWs into our data files.

**Comment by bhazelton** [comment]
This was significantly addressed in PR #104, but to close the issue we need to get it working with the correlator to make sure it meets all the needs.

**Comment by bhazelton** [comment]
Is this done? @jack-h

**Comment by jack-h** [comment]
To my knowledge the UVWs in the data files are currently correct.

**Comment by bhazelton** [comment]
Ok, I'll closing it. @david-deboer since this is marked as a milestone, I thought I should ping you when I closed it, but it was technically done a month or more ago.
