### ISSUE TITLE
Deploy case-insensitive collation for CM databases, or work around inability to do so

### ISSUE THREAD

**Issue by pkgw** [HERA-Team/hera_mc#38]
The version of Postgres that we're using *should* make it possible to set a policy such that text searches on the CM database are case-insensitive by default, which would be nice to have since users might capitalize various parameters that they input to the CM system. Thus far, however, @david-deboer has been unable to get this working.

If we determine that there's some reason that really makes this impossible to deploy, we should come up with some scheme that makes things simple and reliable for users. For example, we could adopt a policy that all text items in the database are written without capital letters, always.

**Comment by bhazelton** [comment]
@david-deboer Should this issue still be open?

**Comment by david-deboer** [comment]
This was also fixed today.
