### ISSUE TITLE
Fix/add to write_records_to_file script.

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_mc#387]
The write_records_to_file script has an incorrect "valid_table" entry and is missing tables.

**Comment by david-deboer** [comment]
The incorrect entry is 'ant_metric', which should be 'ant_metrics' and also the method etc are wrong (look to be cut-pasted from entry above).

Not all of the missing tables need to be covered.  For completeness, here is a list of the missing tables, some of which should probably be included:
alembic_version
apriori_antenna
array_metrics
autocorrelations
cm_version
connections
correlator_config_file
dubitable
geo_location
metric_list
paper_temperatures
part_info
parts
roach_temperature
station_type

**Comment by bhazelton** [comment]
@david-deboer most of these tables don't have an existing method on MCSession that calls the `_time_filter` method, which is required under this script's paradigm. That actually includes `ant_metrics` so it should not have been included in the dict at all.

**Comment by bhazelton** [comment]
I will make a PR to take it out entirely. We could add an appropriate method, but I'll leave that until someone wants it.

**Comment by david-deboer** [comment]
PR removing dict entry merged with master.
