### ISSUE TITLE
convert `get_ant_metric` and `get_array_metric` to use `_time_filter`

### ISSUE THREAD

**Issue by bhazelton** [HERA-Team/hera_mc#397]
To make it uniform with other methods and to allow for integration with `write_records_to_file` script.

**Comment by bhazelton** [comment]
@adampbeardsley are you willing to take this on?

**Comment by bhazelton** [comment]
@adampbeardsley @mkolopanis Do either of you want to tackle this or should I do it?

**Comment by adampbeardsley** [comment]
I can put this on my docket for monday. I'm pretty out of the loop on mc, but I'll give it a try.

**Comment by bhazelton** [comment]
done in #558
