### ISSUE TITLE
Many branches - delete geo-hookup

### ISSUE THREAD

**Issue by david-deboer** [HERA-Team/hera_mc#411]
There are a lot of branches - can we cull?  I'd like to delete the geo-hookup branch, but don't see how to do it.

**Comment by bhazelton** [comment]
One of the easiest ways is to go to the closed PR and scroll to the bottom and click the `delete branch` button. I always do that after I merge PRs.

**Comment by bhazelton** [comment]
Looks like this is cleaned up now.
