### ISSUE TITLE
gps2epoch broken because of year 2038 problem

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#425]
When the correlator breaks, it goes into the future (we've most commonly seen dates ca. 2162). 
 This breaks gps2epoch, a function in the hera_mc postgresql db.

Dates past 2038 overflow 32bit integers.
see eg. https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by mkolopanis** [comment]
I've defined a bigint version of gps2epoch now so we should call all it with bigint for obsid now
