### ISSUE TITLE
add power override table?

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#432]
When we take an item under M&C power control out of service, we should be able to override any commands to power it on.
Suggest some kind of "service_active" or "power_override" table that is checked before any item is commanded on. I'm picturing a single table with columns: part (fk to parts table), power state (Boolean), last_updated.... 

Hang on, is it possible we should just be using CM here?  Why try to turn something on that isn't "connected"?

**Comment by bhazelton** [comment]
This no longer applies give the re-work to the interfaces to not use M&C to actually command anything.
