### ISSUE TITLE
Put snap hostname in M&C

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#498]
At the present time one must construct the snap hostname by looking at the node and slot locations of the snap.   There are several reasons why this is less than ideal. First it is an implicit algorithm, there is no guarantee that the correlator internally will adhere to this algorithm. ie if someone moves a snap from one node to another, they must change both M&C _and_ the hostname in hera-snap-head:/etc/hosts .  Second the query is slow and one of the reasons why the [grafana antenna ownership table](https://enterprise.sese.asu.edu:8484/d/mV2iZUPWk/apriori-status?orgId=1&refresh=1m) takes a while to load.

@bhazelton would like to find a better way.

**Comment by david-deboer** [comment]
The /etc/hosts stuff above is part of the "config" stuff we spoke about.  We could contain it all in this issue.

**Comment by david-deboer** [comment]
This is related to issue #499

**Comment by david-deboer** [comment]
This is being done in PR #500
