### ISSUE TITLE
Verify that F engine "EQ" coefficients are optimal

### ISSUE THREAD

**Issue by david-macmahon** [HERA-Team/hera_mc#503]
The HERA F engine re-quantizes the PFB output values to 4 bits for both the real and imaginary components.  The re-quantization is performed by rounding the 18-bit (or more?) PFB outputs to the top 4 bits.  To accommodate PFB output values that may not be large enough to excite these upper four bits (beyond just being sign extension bits), the F engine multiplies the PFB output values with "EQ" (equalization) coefficients that can be specified at runtime.  Setting these EQ coefficients properly is essential to ensure that the (re-)qauntization to four bits does not introduce non-linearities or other distortions to the 4-bit F engine outputs (aka X engine inputs).  Proper setting of these coefficients can and should be verified by back-calculating the 4-bit RMS values from the integrated autocorrelation values.  For proper functioning of the correlator it is imperative that the resultant 4-bit RMS values are within the desired (i.e. linear) range.

As detailed in the [2007 memo by Don Backer](https://github.com/casper-astro/publications/blob/master/Memos/files/p011.quant.pdf), the optimal setting of the EQ coefficients will result in the RMS of the 4-bit re-quantized output being somewhere between 2 and 3 counts (referred to as "deltas" in the memo). This corresponds to an output variance ranging from 8 to 18.  Operating the correlator outside this range will result in hard/impossible to interpret (i.e. hard/impossible to calibrate) results.

The RMS (or its square, variance) of the 4-bit values can be easily computed from the integrated autocorrelations.  The value of an autocorrelation integrated for N samples is `N * (re_n^2 + im_n^2)`, where `re_n` and `im_n` are the real and imaginary input samples that get correlated.  Assuming that `re_n` and `im_n` have the same variance `sigma^2`, the autocorrelation value is `2N * sigma^2`.  Because the X engine fluffs the 4-bit values to 8-bit values by multiplying them by 16 (i.e. left shifting by 4 bits), the value of `sigma` is actually 16 times the RMS of the 4-bit values.  This leads to the following formula:

    RMS_4bit = sqrt(autocorrelation/(2*N)) / 16

The value of `RMS_4bit` can be computed for each channel of each autocorrelation and plotted to produce an `RMS_4bit` spectrum plot for all antennas.  @dgorthi did this from a data file of a recent observation and produced the following plot:

![Recent 4-bit RMS plot](https://user-images.githubusercontent.com/730406/91144341-bf60c980-e668-11ea-8107-9d5babd6ebae.png)

From this plot it is readily apparent that none of the 4-bit F engine outputs (aka X engine inputs) are within the range of linearity outlined in the memo linked above.  In fact, the vast majority of inputs are in the extremely non-linear range below a 4-bit RMS of 1 across the entire band.  This will lead to distorted results that will be hard/impossible to interpret correctly.  Clearly the current EQ coefficient settings are deficient and in need of revision.

Having the ability to produce such plots on "live data" at runtime is very useful for helping to determine optimal EQ coefficient values.  Having the ability to produce such plots from data files is important for verifying the validity of the data in the dataset.  The script that @dgorthi used to produce that plot should be enhanced to perform both those functions and then included into the suite of diagnostic tools used to validate both proper functioning the correlator at runtime and the quality of the datasets after they have been written to disk, including after they have been copied to the data archive.

The implicit side effect of this is that diagnostic tool just described should be used to determine the optimal EQ coefficients and those new coefficients should replace the current values that led to the plot shown above.

**Comment by bhazelton** [comment]
closing in favor of the linked commissioning issue, where this really belongs.
