### ISSUE TITLE
update write_antenna_locations_file.py

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#55]
Currently fails with

`(HERA) djacobs@hayek:hera_mc (master)$ scripts/write_antenna_location_file.py 
Traceback (most recent call last):
  File "scripts/write_antenna_location_file.py", line 20, in <module>
    locations = geo_handling.get_all_locations(args)
AttributeError: 'module' object has no attribute 'get_all_locations'
`

Also probably needs to be updated to handle gpsseconds.

**Comment by bhazelton** [comment]
Fixed in PR #58.
