### ISSUE TITLE
geo.py shows some antenna numbers as NA

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#56]
![image](https://user-images.githubusercontent.com/63191/28598702-39f2c996-715a-11e7-9fef-405fef57202b.png)
geo.py -g --date=2016/3/10 --time=1:00

**Comment by david-deboer** [comment]
THis is not a bug -- show_state will either show 'all' or 'active'.  If 'all' and antenna not active it shows NA.  Note that the test for 'active' needs to/will change.

**Comment by dannyjacobs** [comment]
What is the current test for activity?
