### ISSUE TITLE
According to M&C, antenna 6 active during H19 but its not in any of our data.

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#57]
![image](https://user-images.githubusercontent.com/63191/28598715-58aa86ee-715a-11e7-8de6-5ed750feb9ef.png)
According to M&C, Antenna 6 (HH51) was turned on and connected same time as the rest of H19, but we don't have it in our data. I've had to explicitly exclude it from CM integration tests over at hera_cal (because its not in our test data file), but would be nice to not have to do that.

**Comment by bhazelton** [comment]
Has this been resolved?

**Comment by bhazelton** [comment]
@dannyjacobs @david-deboer this issue is very old. Has it been resolved?

**Comment by pkgw** [comment]
Gonna close this due to long-term inactivity. Can always reopen if needed.

**Comment by dannyjacobs** [comment]
Ugh H0C?  Lets forget this ever happened.
