### ISSUE TITLE
monitor correlator catcher most recent file

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/hera_mc#625]
meeting with @AaronParsons and @plaplant they request observers to check the current catcher status and the current file being written. We believe the catcher status to be correctly reporting out to the "Currently Recording" box, but not the file. This issue captures progress towards logging the catcher file writing.

Currently recording box on heranow.
<img width="380" alt="image" src="https://user-images.githubusercontent.com/63191/188928968-00e45953-d763-409c-b038-abeb37020946.png">

As of today, the correlator catcher thread is now reporting its most recent file written.   @plaplant reports "the catcher thread is now writing to a new redis key corr:current_file. there is a filename field and a time field. I have installed the latest version of catcher_revamp branch on site"

@bhazelton if you can get this going to the catcher M&C table I will plumb it out to the dashboard

**Comment by mkolopanis** [comment]
Not to detract from getting this info in to M&C, but we can add this to the little system summary box you've highlighted already. it is using grafana to make queries straight from redis.

**Comment by dannyjacobs** [comment]
Yes. Thats the idea. Other dashboards too.

**Comment by bhazelton** [comment]
@dannyjacobs it seems to me like this needs to be in a new table, it doesn't readily fit into the existing tables. The only one I could see working it into is `correlator_component_event_time` but then I'd need to add a column for the filename.

What are your thoughts?
